from flask import Flask, request, jsonify, send_from_directory
from pathlib import Path


# ==========================================
# Flask Application
# ==========================================

app = Flask(__name__)


# ==========================================
# Data Storage
# ==========================================

zones = []


# ==========================================
# Robot Vacuum UI
# ==========================================

@app.route("/")
def index():

    app_directory = (
        Path(__file__).parent.parent
        / "01_UI_Automation"
        / "Playwright"
        / "app"
    )

    return send_from_directory(
        app_directory,
        "robot_vacuum.html"
    )


# ==========================================
# Create No-Go Zone
# ==========================================

@app.route("/api/zones", methods=["POST"])
def create_zone():

    data = request.get_json()

    floor_id = data.get("floor_id")
    name = data.get("name")


    # Required field validation

    if not floor_id or not name:

        return jsonify({
            "error": "floor_id and name are required"
        }), 400


    # Zone ID is generated by the server

    zone_id = f"Z{len(zones) + 1:03d}"


    zone = {

        "zone_id": zone_id,

        "floor_id": floor_id,

        "name": name,

        "status": "active"

    }


    zones.append(zone)


    return jsonify(zone), 201


# ==========================================
# Get No-Go Zones
# ==========================================

@app.route("/api/zones", methods=["GET"])
def get_zones():

    return jsonify(zones), 200





# ==========================================
# Delete No-Go Zone
# ==========================================

@app.route("/api/zones/<zone_id>", methods=["DELETE"])
def delete_zone(zone_id):

    # ==========================================
    # Find Zone
    # ==========================================

    zone = next(
        (
            zone
            for zone in zones
            if zone["zone_id"] == zone_id
        ),
        None
    )


    # ==========================================
    # Zone Not Found
    # ==========================================

    if zone is None:

        return jsonify({
            "error": "Zone not found"
        }), 404


    # ==========================================
    # Delete Zone
    # ==========================================

    zones.remove(zone)


    # ==========================================
    # Delete Success
    # ==========================================

    return jsonify({
        "message": "Zone deleted successfully",
        "zone_id": zone_id
    }), 200




# ==========================================
# Update No-Go Zone
# ==========================================

@app.route("/api/zones/<zone_id>", methods=["PUT"])
def update_zone(zone_id):

    data = request.get_json()

    name = data.get("name")
    floor_id = data.get("floor_id")

    zone = next(
        (
            zone
            for zone in zones
            if zone["zone_id"] == zone_id
        ),
        None
    )

    if zone is None:
        return jsonify({
            "error": "Zone not found"
        }), 404

    if not name or not floor_id:
        return jsonify({
            "error": "floor_id and name are required"
        }), 400

    zone["name"] = name
    zone["floor_id"] = floor_id

    return jsonify(zone), 200



# ==========================================
# Start Flask Server
# ===================================a=======

if __name__ == "__main__":

    app.run(
        host="127.0.0.1",
        port=5000,
        debug=False
    )
    
    