pipeline {
    agent any

    environment {
        PYTHON = 'C:\\Users\\kinga\\AppData\\Local\\Programs\\Python\\Python312\\python.exe'
    }

    stages {

        stage('Checkout') {
            steps {
                echo '=========================================='
                echo 'Checkout Source Code'
                echo '=========================================='

                checkout scm
            }
        }

        stage('Environment Check') {
            steps {
                echo '=========================================='
                echo 'Environment Check'
                echo '=========================================='

                bat '"%PYTHON%" --version'
                bat '"%PYTHON%" -m pip --version'
            }
        }

        stage('Install Dependencies') {
            steps {
                echo '=========================================='
                echo 'Install Dependencies'
                echo '=========================================='

                bat '"%PYTHON%" -m pip install -r requirements.txt'
            }
        }

        stage('Start Mock Server') {
            steps {
                echo '=========================================='
                echo 'Start Mock Server'
                echo '=========================================='

                bat 'start "Robot Mock Server" /B "C:\\Users\\kinga\\AppData\\Local\\Programs\\Python\\Python312\\python.exe" 02_API_Automation/mock_server/robot_api.py

                echo 'Waiting for Mock Server...'

                bat '''
                    powershell -NoProfile -Command "for ($i = 0; $i -lt 20; $i++) { if (Test-NetConnection -ComputerName '127.0.0.1' -Port 5000 -InformationLevel Quiet) { Write-Host 'Mock Server is ready'; exit 0 }; Start-Sleep -Seconds 1 }; Write-Error 'Mock Server failed to start'; exit 1"
                '''
            }
        }

        stage('API Test') {
            steps {
                echo '=========================================='
                echo 'Robot Wi-Fi Reconnect API Test'
                echo '=========================================='

                bat '"%PYTHON%" -m pytest 02_API_Automation/tests/ -s'
            }
        }
    }

    post {

        always {
            echo '=========================================='
            echo 'Jenkins Pipeline Finished'
            echo '=========================================='
        }

        success {
            echo 'TEST RESULT : PASS'
        }

        failure {
            echo 'TEST RESULT : FAIL'
        }
    }
}

